### PR TITLE
install ffmpeg

### PR DESCRIPTION
**Pull request by matt2legit**
I submitted a support request about ffmpeg support on modulus servos and I was advised to open a pull request.  I basically pulled this code from your [base run image](https://github.com/onmodulus/docker-run-base) repo and tested it by building and running docker locally.

### CODE REVIEW

**Comment by theworkflow** [comment]
Hey @matt2legit. Once again, we do apologize for getting so behind on this. Is this currently up to date? Asking in regards to ffmpeg version and what not.

**Comment by theworkflow** [comment]
I want to check out the security of this dependency and make sure it doesn't have any security risks

**Comment by matt2legit** [comment]
No worries.  It appears to be version 3.2.2 of ffmpeg, which is the latest release.

**Comment by theworkflow** [comment]
Hey @matt2legit. Once again, sorry for the delay. Is there a reason for not installing the package using `apt-get`? https://launchpad.net/~mc3man/+archive/ubuntu/trusty-media

**Comment by matt2legit** [comment]
@theworkflow I think I tried this and was having trouble getting ffmpeg to install after I added the package archive.  I can certainly try again if you feel this is the best way.  Just let me know.

Again, the way I proposed was taken from an image you guys previously used and it worked great, so I rolled with.

**Comment by theworkflow** [comment]
Hm... Can you update the PR and post the output that you're getting @matt2legit?

**Comment by matt2legit** [comment]
Hey @theworkflow, let me know if my update looks better to you.  Thanks!

**Comment by theworkflow** [comment]
`ffmpeg` looks to be installed in the [base run image](https://github.com/XervoIO/docker-run-base/blob/master/bootstrap.sh#L52). Closing this PR

**Pull request closed without merging**
